FROM nginx:alpine

# Remove the default NGINX configuration
# RUN rm /etc/nginx/sites-enabled/default

# Copy the NGINX configuration file into the container
# COPY nginx.conf /etc/nginx/sites-available/
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY certs /etc/ssl/certs

# Link the NGINX config file
# RUN ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/

# Expose port 443 to the outside world
# EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]